package com.pavco.org.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ProductTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductTypeAllPropertiesEquals(ProductType expected, ProductType actual) {
        assertProductTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertProductTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductTypeAllUpdatablePropertiesEquals(ProductType expected, ProductType actual) {
        assertProductTypeUpdatableFieldsEquals(expected, actual);
        assertProductTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductTypeAutoGeneratedPropertiesEquals(ProductType expected, ProductType actual) {
        assertThat(expected)
            .as("Verify ProductType auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductTypeUpdatableFieldsEquals(ProductType expected, ProductType actual) {
        assertThat(expected)
            .as("Verify ProductType relevant properties")
            .satisfies(e -> assertThat(e.getUuid()).as("check uuid").isEqualTo(actual.getUuid()))
            .satisfies(e -> assertThat(e.getCode()).as("check code").isEqualTo(actual.getCode()))
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getPrice()).as("check price").isEqualTo(actual.getPrice()))
            .satisfies(e -> assertThat(e.getDiscount()).as("check discount").isEqualTo(actual.getDiscount()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertProductTypeUpdatableRelationshipsEquals(ProductType expected, ProductType actual) {}
}
